### ISSUE TITLE
How do I run the whole test suite?

### ISSUE THREAD

**Issue by jhsu802701** [novu/whale-of-a-tale#7] opened 2019-09-13 15:12 UTC
What are the commands for running the whole test suite?  If the app used Travis CI, CircleCI, or some other continuous integration solution that provides a build status badge, that would clue me in on the full procedure for setting things up.

**Comment by arich** [comment] 2019-09-16 14:43
@jhsu802701 I'd challenge you to submit a PR to add in TravisCI or CircleCI support. 
We use CircleCI at Novu, so CircleCI would be preferred. 

This seems like a duplicate of https://github.com/novu/whale-of-a-tale/issues/5.

**Comment by arich** [comment] 2020-09-16 13:37
Closing due to inactivity.

**Closed by arich** 2020-09-16 13:37 UTC
